version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  Test:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
          install-npm: false
      - run:
          name: Yarn test
          command: yarn test
workflows:
  run-and-test:
    jobs:
      - Test
