version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/repo

    steps:
      - checkout
      - run:
        - name: Update node to v8.11.1
        - shell: /bin/sh
        - command: nvm install v8.11.1

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
